services:

  be-apirest:
    image: ${COMPOSE_PROJECT_LEAD}-${COMPOSE_PROJECT_NAME}:${COMPOSE_PROJECT_IMGK}
    pull_policy: never
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${COMPOSE_PROJECT_USER}
        - GROUP=${COMPOSE_PROJECT_GROUP}
    container_name: ${COMPOSE_PROJECT_LEAD}-${COMPOSE_PROJECT_NAME}
    ports:
      - ${COMPOSE_PROJECT_PORT}:80
    volumes:
      - type: bind
        source: ${COMPOSE_PROJECT_PATH}
        target: /var/www
    deploy:
      resources:
        limits:
          memory: ${COMPOSE_PROJECT_MEM}
    tty: true
    restart: unless-stopped
